version: "3"

services:
  postgresql:
    image: postgres:12
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432
    volumes:
      - ${PWD}/postgresql/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ${PWD}/postgresql/2-prenoms.sql:/docker-entrypoint-initdb.d/2-prenoms.sql
    environment:
      POSTGRES_DB:       prenoms
      POSTGRES_USER:     prenoms
      POSTGRES_PASSWORD: prenoms

  server:
    depends_on:
      - postgresql
    image: prenoms
    build:
      context: server
      args:
        - PIP_ENV=development
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - APP_PREFIX=/api
      - DB_HOST=postgresql
      - DB_USER=prenoms
      - DB_PASS=prenoms
      - DB_NAME=prenoms
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    volumes:
      - ${PWD}/server/app:/code/app:ro
      - ${PWD}/server/main.py:/code/main.py:ro
    ports:
      - 8000:8000

  nginx:
    image: nginx
    depends_on:
      - server
      #- frontend
    volumes:
      - ${PWD}/server/htmlcov:/coverage:ro
      - ${PWD}/nginx/nginx.conf.development:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
