version: '3'

services:
  postgresql-testing:
    image: postgres:12
    volumes:
      - ${PWD}/../postgresql/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
      POSTGRES_DB:       prenoms-testing
      POSTGRES_USER:     prenoms-testing
      POSTGRES_PASSWORD: prenoms-testing

  tests:
    image: prenoms
    build:
      args:
        PIP_ENV: development
    depends_on:
      - postgresql-testing
    environment:
      # Development
      APP_ENV: 'tests'
      APP_DEBUG: 'true'

      # PostgreSQL
      DB_HOST: postgresql-testing
      DB_USER: prenoms-testing
      DB_PASS: prenoms-testing
      DB_NAME: prenoms-testing
    command: [ "pytest", "--cov=app/", "--cov-report=term", "--cov-report=html", "tests/" ]
    volumes:
      - ${PWD}:/code
